language: python
python:
  - '3.6'
#
#install:
#  - pip install .
env:
  global:
    - secure: mcUCykGm4bUZ3CaW6AxrIMFzuAYjA98VIz6YmYTmM0/8sp/B/54JtQS/j0ehCD6B5BwyW6diVcaQA2c7bovI23GyeTT+TgfkuKRkzDcoY51ZsMDdsflJ94zV7TEIS31eCeq42IBYdHZeVZp/L7EXOzFjVmvYhboJiwnsPybpCfpIH369fjYKuVmutccD890nP8Bzg8iegssVldgsqDagkuLy0wObAVH0FKnqiIPtFoMf3mDeVmK2AkF1Xri1edsPl4wDIu1Ko3RCRgfr6NxzuNSh6f4Z6zmJLB4ONkpb3fAa9Lt+VjJjdSjCBT1OGhJdP7NlO5vSnS5TCYvgFqNSXqqJx9BNzZ9/esszP7DJBe1yq1aNwAvJ7DlSzh5rvLyXR4VWHXRIR3hOWDTRwCsJQJctCLpbDAFJupuZDcvqvPNj8dY5MSCu6NroXMMFmxJHIt3Hdzr+hV9RNJkQRR4K5bR+ewbJ/6h9rjX6Ot6kIsjJkmEwx1jllxi4+gSRtNQ/O4NCi3fvHmpG2pCr7Jz0+eNL2d9wm4ZxX1s18ZSAZ5XcVJdx8zL4vjSnwAQoFXzmx0LcpK6knEgw/hsTFovSpe5p3oLcERfSd7GmPm84Qr8U4YFKXpeQlb9k5BK9MaQVqI4LyaM2h4Xx+wc0QlEQlUOfwD4B2XrAYXFIq1PAEic=

script: env

#jobs:
#  fast_finish: true
#  include:
#  - stage: deploy
#    name: Deploy to PyPI
#    python: '3.6'
#    deploy:
#      provider: pypi
#      user: riscure
#      password:
#        secure: slvfH457ETn60MtvxLpIIicpzC8RrHmMHpwo8MWH9s93DxZhEyBWKr6jVOaJd5ZlO0fRL2hfhFA1RPqg+IB/84cPwXBmJ2n7c3Wfx/ORu9cRwXqC9W8pnthUpRd8sw8BD+HCg4YY3EkWvU/NRfKGejd69p6PbyzAWpwAZlXMeQsmHyuuVfNrTm4sXK6p28OOD3/FGPfGW7PoytQeg7M0f0JbhLTMlLcV/97hjLTPsPmhFwhi+Q7qZ5eptpFpWsGuCDKs8kI87t+4cSgMPdO5nPPb+UA5BmoAM7II7Nl0EZiSYsRFUggr4LxchtUPd4DziAC7Kymk/aRinVkny1LR8WNqNwidwoGifYiudE11S/rdGTjMER+72M0QVc4aTwkVgpcH8iChQYG4jYmndFdSCstSMl9MaWURX1z64aEw1Rm0Tda9vNhbHn6SH7EagryffG7agO9jReusA7z9kxWL20H9rcDFzAeG/kaB16lFurXH31VXqfO86KkrQFR639VMtYGN/ouXY03bhXW22HzECBWs7xyCGvsj754+jcyZFzNVSsaCHD+D285JkUvpJXBAy8TCWpi+nKFev3DXU3+fJDDcXJNALfUBgMKe+LNHYbOF6074p9FPWHvqWAnlJ+Gu42wES7UGwqw9p8R2+H8+jqLJ+VimeIS0pZY5bfstHms=
#      distributions: sdist bdist_wheel
#      on:
#        tags: true
